apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-app-with-error
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: helm-guestbook-with-error
    repoURL: https://github.com/testcodefresh/argocd-example-apps.git
    targetRevision: olek
  destination:
    name: in-cluster
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
