apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-canary-ingress
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/oleksandr-codefresh/canary-rollout
    targetRevision: k8s-1.22
  destination:
    name: in-cluster
    namespace: test-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
