apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-canary-rollout
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: canary-rollout-ingress
    repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps.git
    targetRevision: eks-local
  destination:
    server: https://kubernetes.default.svc
    namespace: test-namespace
  syncPolicy:
    automated:
      prune: true
#       selfHeal: true
    syncOptions:
      - CreateNamespace=true
